version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12.7
    steps:
      - checkout
      - run:
          name: Install Packages
          command: |
            pip install pytest
            pip install requests
      - run:
          name: Run Unit Tests for TestTriangle
          command: |
            pytest --junitxml=test-results/results.xml "HW02a -- Testing A Legacy Program/TestTriangle.py"
      - run:
          name: Run Unit Tests for TestGetReposAndCommits
          command: |
            pytest --junitxml=test-results/results.xml "HW04a -- Develop with Perspective of Tester in Mind/TestGetReposAndCommits.py"
      - run:
          name: Run Unit Tests for Mock TestGetReposAndCommits
          command: /
            pytest --junitxml=test-results/results.xml "HW05a -- Isolate External Dependencies"
      - store_test_results:
          path: test-results

workflows:
  testing_suite:
    jobs:
      - build-and-test
